Updating things that really have should been in main and the import and fixes tbh
2531RoboHawks/SwerveDrive pull request #7
Opened 2023-02-19 23:40 UTC by WaterGame2023

Basically I was just stupid and realized that the `whenPressed` method was deprecated and should be replaces with `onTrue` or `whenTrue` Also the gyro is no longer inverted so that got changed in constants.

2023-02-19 23:42 UTC, WaterGame2023 commented
Oh yeah @SilverBulletO1 the invert gyro is the change I walked you through on the phone because swerve would not turn right. I just missed it with the initial imports to 2023.

2023-02-20 00:07 UTC, daonguyenk06 commented on src/main/java/frc/robot/RobotContainer.java
> +    zeroGyro.onTrue(new InstantCommand(() -> swerveSubsystem.zeroGyro()));
Can you leave a comment on what onTrue does instead of whenPressed? That might help some of us.

2023-02-20 14:15 UTC, 25kingk requested changes, later dismissed
You likely need more comments. While I understand the change, others might not and explaining some of the more complex or confusing code would probably be a good thing.

2023-02-20 17:17 UTC, 42daha commented on src/main/java/frc/robot/Constants.java
> +        public static final boolean invertGyro = false; // Is the GYRO Upside Down?
Does the pidgeon care?  Having a comment to explain would be nice.

2023-02-20 17:18 UTC, 42daha approved these changes

2023-02-20 21:46 UTC, Trex1620 approved these changes

2023-02-20 21:48 UTC, Trex1620 approved these changes

2023-02-20 21:49 UTC, LemonHead2114 approved these changes
I

2023-02-20 21:54 UTC, merged